"""empty message

Revision ID: 515621c38927
Revises: a7bc0c3488d7
Create Date: 2023-08-30 18:56:57.408087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '515621c38927'
down_revision = 'a7bc0c3488d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favourite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_user', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('id_peoples', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('id_planets', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('id_vehicles', sa.Integer(), nullable=True))
        batch_op.drop_constraint('favourite_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'vehicle', ['id_vehicles'], ['id'])
        batch_op.create_foreign_key(None, 'planet', ['id_planets'], ['id'])
        batch_op.create_foreign_key(None, 'people', ['id_peoples'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['id_user'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_constraint('people_favourite_id_fkey', type_='foreignkey')
        batch_op.drop_column('favourite_id')

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_constraint('planet_favourite_id_fkey', type_='foreignkey')
        batch_op.drop_column('favourite_id')

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_constraint('vehicle_favourite_id_fkey', type_='foreignkey')
        batch_op.drop_column('favourite_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favourite_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('vehicle_favourite_id_fkey', 'favourite', ['favourite_id'], ['id'])

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favourite_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('planet_favourite_id_fkey', 'favourite', ['favourite_id'], ['id'])

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favourite_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('people_favourite_id_fkey', 'favourite', ['favourite_id'], ['id'])

    with op.batch_alter_table('favourite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favourite_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_column('id_vehicles')
        batch_op.drop_column('id_planets')
        batch_op.drop_column('id_peoples')
        batch_op.drop_column('id_user')

    # ### end Alembic commands ###
