"""empty message

Revision ID: 68db1388cfd3
Revises: a71cf42ac251
Create Date: 2023-08-31 13:11:36.727068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68db1388cfd3'
down_revision = 'a71cf42ac251'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favourite', schema=None) as batch_op:
        batch_op.drop_constraint('favourite_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favourite', schema=None) as batch_op:
        batch_op.create_unique_constraint('favourite_name_key', ['name'])

    # ### end Alembic commands ###
