"""empty message

Revision ID: a7bc0c3488d7
Revises: 5469bbf1321e
Create Date: 2023-08-29 20:21:41.668778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7bc0c3488d7'
down_revision = '5469bbf1321e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('favourite_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('favourite_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.alter_column('favourite_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.alter_column('favourite_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('favourite_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('favourite_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
