"""empty message

Revision ID: c0659762a3ae
Revises: 58de4592bb5e
Create Date: 2023-09-04 15:34:53.791527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0659762a3ae'
down_revision = '58de4592bb5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('rotation_period',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('orbital_period',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('diameter',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('climate',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('gravity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('terrain',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('surface_water',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('population',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.alter_column('population',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('surface_water',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('terrain',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('gravity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('climate',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('diameter',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('orbital_period',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('rotation_period',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
