"""empty message

Revision ID: d390d7060072
Revises: d2afbe942246
Create Date: 2023-08-29 19:54:43.685958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd390d7060072'
down_revision = 'd2afbe942246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favourite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('rotation_period', sa.Integer(), nullable=False),
    sa.Column('orbital_period', sa.Integer(), nullable=False),
    sa.Column('diameter', sa.Integer(), nullable=False),
    sa.Column('climate', sa.String(length=250), nullable=False),
    sa.Column('gravity', sa.Float(precision=50), nullable=False),
    sa.Column('terrain', sa.String(length=250), nullable=False),
    sa.Column('surface_water', sa.Integer(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('favourite_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['favourite_id'], ['favourite.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favourite_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('people_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'favourite', ['favourite_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favourite_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'favourite', ['favourite_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('favourite_id')

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('people_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_column('favourite_id')

    op.drop_table('planet')
    op.drop_table('favourite')
    # ### end Alembic commands ###
